DROP DATABASE IF EXISTS tweetdrafter;
CREATE DATABASE tweetdrafter
	DEFAULT CHARACTER SET utf8 DEFAULT
	COLLATE utf8_general_ci;
USE tweetdrafter;

CREATE TABLE users(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(15) NOT NULL UNIQUE,
	PASSWORD CHAR(40)
)ENGINE=innoDB;

CREATE TABLE tweets(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FKUSER_ID INT UNSIGNED,
	CONTENT VARCHAR(1024) NOT NULL,

	FOREIGN KEY(FKUSER_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=innoDB;

ALTER TABLE users AUTO_INCREMENT = 1;
